### ISSUE TITLE
ASP.NET MVC + Blazor предлагаю заменить на Asp.Net Web Api +Blazor

### ISSUE THREAD

**Issue by LightVolk** [sbzenenko/DeveloperPathAbout#4]
Как вариант, предлагаю изменить MVC на Web Api. 
А клиента уже делать отдельно от сервера. То есть, он может быть как клиентским Blazor, так и божественным Angular SPA.

Заодно и научимся проектировать API\взаимодействие со фронтом. Проблемы между фронтом (дайте простые данные) и беком (а мне удобнее вот так отдать).

**Comment by sbenzenko** [comment]
Принято
